on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    - name: Create Release
    - uses: taiki-e/create-gh-release-action@v1
      with:
        title: Opera $tag
        changelog: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  releases-matrix:
    name: Build Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    - uses: wangyoucao577/go-release-action@v1.21
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: circleload
        extra_files: LICENSE README.md
